[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bank = "FiWfkSEsfkChcYvn42cWGpPKYga7qFEWX26Sx78TXmBr"
big-accounts = "CVgWZ6G6DdvTaqQtzZiWs8k5qjDynxECC1KRkZWjRPGc"
counter = "J5RWjigXEQfW3WrykWAsJvb58MqhDM8pqJBzVaWEFiAs"
full_stack_solana = "HBq27XcCHHCyXbaVwacJyk6DpDTKfa2AnrcDrYEr48x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
