cargo-features = ["edition2024"]
[package]
name = "getting-started"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true

[dev-dependencies]
litesvm.workspace = true
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]



