cargo-features = ["edition2024"]
[package]
name = "counter-nativ"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh.workspace = true
solana-program.workspace = true

[dev-dependencies]
litesvm.workspace = true
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

